name: Kits
main: com.asylumsw.bukkit.kits.Kits
version: 2.0.1
author: Jonathan Borzilleri
description: >
             Allows groups of items to be spawned.
commands:
  kit:
    description: Spawn an item kit, or list all kits.
    usage: |
           /<command> list
           /<command> <kit name>
           Example: /<command> pick - spawns the 'pick' kit.